### ISSUE TITLE
无法使用定时任务功能咨询

### ISSUE THREAD

**Issue by Harry-S** [AngelLiang/celery-sqlalchemy-scheduler#1]
您好，
    我这边已经对celery_periodic_task表作了任务设计，定义了crontab_id的对应值，然后激活该任务。但是发现 beat 日志出现 ：Disabling schedule XXX that was removed from database 的错误日志。之后该任务就变回 禁用状态了。该错误应该是没有配置 定时任务标记出现的。但是配置了 crontab_id 有问题，interval_id设置是正常运行的。请问是否有解决方案，谢谢

**Comment by AngelLiang** [comment]
不太明白你意思。你是说你自己加了一张数据表关联 `PeriodicTask.models.PeriodicTask:crontab_id` ？

能否详细说明你做了哪些修改，或者添加了什么，及相关命令步骤？如果我这边能复现你的bug会尝试解决。

**Comment by Harry-S** [comment]
celery的配置信息：
from __future__ import absolute_import
from datetime import timedelta
from celery import Celery

from celery_sqlalchemy_scheduler.schedulers import DatabaseScheduler

broker_url = 'amqp://admin:@127.0.0.1:5672//'
backend = 'amqp://admin:@127.0.0.1:5672//'


beat_schedule = {
    'echo-every-3-seconds': {
        'task': 'tscelery.tasks.echo',
        'schedule': timedelta(seconds=3),
        'args': ('hello', )
    },
}

beat_scheduler = 'celery_sqlalchemy_scheduler.schedulers:DatabaseScheduler'

beat_sync_every = 0


beat_max_loop_interval = 10


beat_dburi = 'mysql+mysqlconnector://xx:yy@127.0.0.1:3306/zz'


timezone = 'Asia/Shanghai'


worker_max_tasks_per_child = 10


app = Celery('tscelery',
			 backend=backend,
			 broker=broker_url,
             include=['tasks']
	    )


config = dict(
    beat_schedule=beat_schedule,
    beat_scheduler=beat_scheduler,
    beat_max_loop_interval=beat_max_loop_interval,
    beat_dburi=beat_dburi,

    timezone=timezone,
    worker_max_tasks_per_child=worker_max_tasks_per_child
)

app.conf.update(config)

if __name__ == '__main__':
	app.start()

----------------------------------------------------------------------------------------------
tasks.py文件信息：
@app.task
def CrontabTask(**kwargs):
    ip = kwargs['ip']
    cmd = kwargs['cmd']
    res = "{0} {1}".format(ip,cmd)
    return res

----------------------------------------------------------------------------------------------


celery_crontab_schedule表：
           id: 1
       minute: *
         hour: *
  day_of_week: *
 day_of_month: *
month_of_year: *
     timezone: Asia/Shanghai

创建的MyB任务信息：
             id: 1
           name: MyB
           task: tscelery.tasks.CrontabTask
    interval_id: NULL
     crontab_id: 1
       solar_id: NULL
           args: []
         kwargs: {"ip": "127.0.0.1","cmd":"date"}
          queue: NULL
       exchange: NULL
    routing_key: NULL
       priority: NULL
        expires: NULL
        one_off: 0
     start_time: 2019-05-23 16:03:19
        enabled: 0
    last_run_at: 2019-05-23 16:46:24
total_run_count: 14
   date_changed: 2019-05-23 19:32:51
    description: 


当我在数据库把enabled状态变更为1，然后刷新 celery_periodic_task_changed表的时间信息就出现以下错误日志（ERROR/MainProcess] Disabling schedule MyB that was removed from database）。再查一次数据库 enabled 状态就变为 0。

beat 错误日志信息输出：
2019-05-23 19:32:50,624: INFO/MainProcess] DatabaseScheduler: Schedule changed.
[2019-05-23 19:32:50,624: INFO/MainProcess] Writing entries...
[2019-05-23 19:32:50,627: ### ERROR/MainProcess] Disabling schedule MyB that was removed from database
[2019-05-23 19:34:20,581: INFO/MainProcess] Writing entries...

**Comment by AngelLiang** [comment]
bug能复现了，正在解决中

**Comment by Harry-S** [comment]
好的，感谢

**Comment by AngelLiang** [comment]
你提的bug应该是解决了，发布了v0.1.1版本。不过我目前又发现新的bug。

目前的代码测试发现，celery == 4.2.0 版本没有问题。
但是在 celery == 4.3.0 版本，如果有 schedule 为 timedelta 的任务，则只会触发这些schedule，会跳过 schedule 为 schedules.crontab() 的任务。

所以目前建议用celery == 4.2.0（4.2.1应该也可以）

测试代码

```python
"""
Run Worker:
    $ celery worker -A demo:app -l info
Run Beat:
    $ celery beat -A demo:app -S demo:DatabaseScheduler -l info
"""

# from future import absolute_import

import os
import platform
from datetime import timedelta
from celery import Celery
from celery import schedules

from celery_sqlalchemy_scheduler.schedulers import DatabaseScheduler

if platform.system() == 'Windows':
    os.environ['FORKED_BY_MULTIPROCESSING'] = '1'

broker_url = 'amqp://guest:guest@127.0.0.1:5672//'
backend = 'rpc://'

# celery == 4.2.0 版本没有问题
# celery == 4.3.0 版本如果有 schedule 为 timedelta 的任务，
# 则只会触发这些schedule，跳过 schedule 为 schedules.crontab() 的任务
beat_schedule = {
    'echo-every-15-seconds': {
        'task': 'demo.echo',
        'schedule': timedelta(seconds=15),
        'args': ('hello', )
    },
    'echo-every-30-seconds': {
        'task': 'demo.echo',
        'schedule': timedelta(seconds=30),
        'args': ('hello', )
    },
    'CrontabTask': {
        'task': 'demo.CrontabTask',
        'schedule': schedules.crontab('*', '*', '*'),
        'kwargs': {'ip': '127.0.0.1', 'cmd': 'ls'}
    },
    'add-every-minutes': {
        'task': 'demo.add',
        'schedule': schedules.crontab('*', '*', '*'),
        'args': (1, 2)
    },
}

beat_scheduler = 'celery_sqlalchemy_scheduler.schedulers:DatabaseScheduler'

beat_sync_every = 0

beat_max_loop_interval = 10

# beat_dburi = 'mysql+mysqlconnector://xx:yy@127.0.0.1:3306/zz'

timezone = 'Asia/Shanghai'

worker_max_tasks_per_child = 10

app = Celery('tscelery',
             backend=backend,
             broker=broker_url,
             #  include=['tasks']
             )

config = dict(
    beat_schedule=beat_schedule,
    beat_scheduler=beat_scheduler,
    beat_max_loop_interval=beat_max_loop_interval,
    # beat_dburi=beat_dburi,

    timezone=timezone,
    worker_max_tasks_per_child=worker_max_tasks_per_child

)

app.conf.update(config)


@app.task
def CrontabTask(**kwargs):
    ip = kwargs['ip']
    cmd = kwargs['cmd']
    res = "{0} {1}".format(ip, cmd)
    return res


@app.task
def echo(data):
    print(data)


@app.task
def add(x, y):
    return x + y


if __name__ == 'main':
    app.start()

```

**Comment by AngelLiang** [comment]
如果没有 schedule 为 timedelta 的任务， schedule 为 schedules.crontab() 的任务则可以触发。

**Comment by Harry-S** [comment]
celery == 4.2.2 验证通过，感谢
