### ISSUE TITLE
Crontab Error

### ISSUE THREAD

**Issue by yapnel** [AngelLiang/celery-sqlalchemy-scheduler#13]
Have defined the below but throwing error. Not sure what i am doing wrong here. Please advise.

> 
        schedule = CrontabSchedule(
              minute='*',
              hour='*',
              day_of_week='*',
              day_of_month='*',
              month_of_year='*',
              timezone=pytz.timezone('Canada/Pacific')              
         )
         session.add(schedule)
         session.commit()
         periodic_task = PeriodicTask(
            crontab=schedule,
            name=racfid+'test-scheduler',
            task='tasks.task.sayHello',
            args=json.dumps([dispatch])
         )
         session.add(periodic_task)
         session.commit()

> sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 5 - probably unsupported type.
[SQL: INSERT INTO celery_crontab_schedule (minute, hour, day_of_week, day_of_month, month_of_year, timezone) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('*', '*', '*', '*', '', <DstTzInfo 'Canada/Pacific' LMT-1 day, 15:48:00 STD>)]
(Background on this error at: http://sqlalche.me/e/rvf5)

**Comment by AngelLiang** [comment]
Sorry, there had some errors in exmaple code. `timezone` shoule be string, not `pytz.timezone(...)`

```
schedule = CrontabSchedule(
          minute='*',
          hour='*',
          day_of_week='*',
          day_of_month='*',
          month_of_year='*',
          timezone='UTC'
     )
```
