### ISSUE TITLE
The enabled interval schedule is not triggering If we add new Periodic Tasks to the database

### ISSUE THREAD

**Issue by DarshanLukhi** [AngelLiang/celery-sqlalchemy-scheduler#19]
The enabled interval schedule is not triggering If we add new Periodic Tasks to the database

I don't know why this happens. 
if any mistake from my side then can you suggest to me?

**Comment by AngelLiang** [comment]
You added new Periodic Tasks by database tool, or by PeriodicTask Model?

you can read [example code 1](https://github.com/AngelLiang/celery-sqlalchemy-scheduler/blob/master/examples/base/tasks.py) for more detail.

```
>>> import json
>>> from celery_sqlalchemy_scheduler.models import PeriodicTask, IntervalSchedule
>>> from celery_sqlalchemy_scheduler.session import SessionManager
>>> beat_dburi = 'sqlite:///schedule.db'
>>> session_manager = SessionManager()
>>> engine, Session = session_manager.create_session(beat_dburi)
>>> session = Session()
# Disable 'echo-every-3-seconds' task
>>> task = session.query(PeriodicTask).filter_by(name='echo-every-3-seconds').first()
>>> task.enabled = False
>>> session.add(task)
>>> session.commit()
>>> schedule = session.query(IntervalSchedule).filter_by(every=10, period=IntervalSchedule.SECONDS).first()
>>> if not schedule:
...     schedule = IntervalSchedule(every=10, period=IntervalSchedule.SECONDS)
...     session.add(schedule)
...     session.commit()
# Add 'add-every-10s' task
>>> task = PeriodicTask(
...     interval=schedule,
...     name='add-every-10s',
...     task='tasks.add',  # name of task.
...     args=json.dumps([1, 5])
... )
>>> session.add(task)
>>> session.commit()
>>> print('Add ' + task.name)
Add add-every-10s
>>> task.args=json.dumps([10, 2])
>>> session.add(task)
>>> session.commit()
```

**Comment by DarshanLukhi** [comment]
@AngelLiang,  I added periodic task PeriodicTask Model.

**Comment by DarshanLukhi** [comment]
`        self.total_run_count = model.total_run_count
        self.enabled = model.enabled

        if not model.last_run_at:
            model.last_run_at = self._default_now()
        self.last_run_at = model.last_run_at

        # 因为从数据库读取的 last_run_at 可能没有时区信息，所以这里必须加上时区信息
        # self.last_run_at = self.last_run_at.replace(tzinfo=self.app.timezone)`
 If i remove above commented line then its working fine.

**Comment by AngelLiang** [comment]
Maybe a bug. you can read this [PR](https://github.com/AngelLiang/celery-sqlalchemy-scheduler/pull/16/commits/416a51fc7492c11c2c67299d498d448d33403afe) for detail.

Some bugs are related to timezones, but I can't fix they well. So welcome PR if you like.

**Comment by AngelLiang** [comment]
I rollback the commented line and release v0.2.6.
Maybe some database don't save timezone throught `sa.DateTime(timezone=True)`.
