### ISSUE TITLE
crontab的任务时间会错误

### ISSUE THREAD

**Issue by xxxss** [AngelLiang/celery-sqlalchemy-scheduler#2]
interval的任务时间没问题，但是如果我在数据库里添加了minute 是 */10的任务，下一次执行时间会是utc时间，比如我是Asia/Shanghai，任务会安排到8个小时以后。。

**Comment by AngelLiang** [comment]
感谢反馈，全力解决中。。。
![](http://wx1.sinaimg.cn/mw690/4bc0e3e7gy1g4y4mkgop5j20c80cfgls.jpg)

**Comment by AngelLiang** [comment]
“添加了minute 是 */10”，你的目的是添加一个“每小时的第10分钟”执行的任务吗？添加好之后，第一次开始执行任务的时间却是在8小时之后而不是最近的小时执行？

**Comment by AngelLiang** [comment]
经过我简单的测试和排查，似乎并没有复现你说的bug，

```
beat_schedule = {
    'echo-every-3-seconds': {
        'task': 'tasks.echo',
        'schedule': timedelta(seconds=3),
        'args': ('hello', )
    },
    'add-every-minutes': {
        'task': 'tasks.add',
        #'schedule': schedules.crontab('*', '*', '*'),
        # 改为：
        'schedule': schedules.crontab('*/2', '*', '*'),
        'args': (1, 2)
    },
}
```

Windows10环境，beat app部分日志如下：

```
> celery beat -A tasks:celery -S tasks:DatabaseScheduler -l info
celery beat v4.2.0 (windowlicker) is starting.
__    -    ... __   -        _
LocalTime -> 2019-07-13 17:37:44
Configuration ->
    . broker -> amqp://guest:**@localhost:5672//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery_sqlalchemy_scheduler.schedulers.DatabaseScheduler
    . db -> sqlite:///schedule.db
    . logfile -> [stderr]@%INFO
    . maxinterval -> 10.00 seconds (10s)
[2019-07-13 17:37:44,360: INFO/MainProcess] beat: Starting...
[2019-07-13 17:37:44,364: INFO/MainProcess] Writing entries...
[2019-07-13 17:37:44,549: INFO/MainProcess] Scheduler: Sending due task echo-every-3-seconds (tasks.echo)
[2019-07-13 17:37:44,574: INFO/MainProcess] Writing entries...
[2019-07-13 17:37:44,650: INFO/MainProcess] Scheduler: Sending due task add-every-minutes (tasks.add)
[2019-07-13 17:37:47,531: INFO/MainProcess] Scheduler: Sending due task echo-every-3-seconds (tasks.echo)
...
[2019-07-13 17:38:00,000: INFO/MainProcess] Scheduler: Sending due task add-every-minutes (tasks.add)
[2019-07-13 17:38:02,535: INFO/MainProcess] Scheduler: Sending due task echo-every-3-seconds (tasks.echo)
...
[2019-07-13 17:40:00,000: INFO/MainProcess] Scheduler: Sending due task add-every-minutes (tasks.add)
[2019-07-13 17:40:02,564: INFO/MainProcess] Scheduler: Sending due task echo-every-3-seconds (tasks.echo)
[2019-07-13 17:40:05,565: INFO/MainProcess] Scheduler: Sending due task echo-every-3-seconds (tasks.echo)
```

以下三个时间点触发了`add-every-minutes`任务。

- 17:37:44,650
- 17:38:00,000
- 17:40:00,000

并没有你说的会延迟8个小时后再触发。

如果可以，请告诉我你具体的测试步骤？

**Comment by xxxss** [comment]
我第一次添加的时候也可以工作，我是直接修改的数据库，在task表里增加了三条（加上默认的clean的一共四条）。其中一个interval的任务每隔17分钟一次，两条是crontab的*/10，然后重新启动beat，就发现只有interval的那个会在heap里排到第一个，17分钟内就会执行，其他的两个cron的都是8个小时以后。
我debug(H) 把heap打印出出来：

[2019-07-13 11:42:09,761: DEBUG/MainProcess] [event_t(time=1562990172.082371, priority=5, entry=<ModelEntry: sometask3 sometask3(*[], **{}) <freq: 17.00 minutes>>), event_t(time=1562990399.9902568, priority=5, entry=<ModelEntry: celery.backend_cleanup celery.backend_cleanup
(*[], **{}) <crontab: 0 4 * * * (m/h/d/dM/MY), UTC>
event_t(time=1563016799.990166, priority=5, entry=<ModelEntry: sometask sometask(*[], **
{}) <crontab: */10 * * * * (m/h/d/dM/MY), UTC>
        >), event_t(time=1563016799.990258, priority=5, entry=<ModelEntry: sometask2 sometask2(*[],
**{}) <crontab: */10 * * * * (m/h/d/dM/MY), UTC>
 >)]

**Comment by xxxss** [comment]
由于我日志是中午11点的，里面的time正好是现在19点多。。其实当时是8个小时以后。。

我自己做了些修改，目前似乎正常了：

diff --git a/celery_sqlalchemy_scheduler/models.py b/celery_sqlalchemy_scheduler/models.py
index 248ef73..82e00ae 100644
--- a/celery_sqlalchemy_scheduler/models.py
+++ b/celery_sqlalchemy_scheduler/models.py
@@ -1,6 +1,7 @@
 # coding=utf-8

 import datetime as dt
+import pytz

 import sqlalchemy as sa
 from sqlalchemy.orm import relationship, foreign, remote
@@ -98,7 +99,7 @@ class CrontabSchedule(ModelBase, ModelMixin):
             hour=self.hour, day_of_week=self.day_of_week,
             day_of_month=self.day_of_month,
             month_of_year=self.month_of_year,
-            # tz=self.timezone
+            tz=pytz.timezone(self.timezone)
         )

     @classmethod
diff --git a/celery_sqlalchemy_scheduler/tzcrontab.py b/celery_sqlalchemy_scheduler/tzcrontab.py
index f8260ab..098db5c 100644
--- a/celery_sqlalchemy_scheduler/tzcrontab.py
+++ b/celery_sqlalchemy_scheduler/tzcrontab.py
@@ -30,10 +30,9 @@ class TzAwareCrontab(schedules.crontab):
         )

     def nowfunc(self):
-        # return self.tz.normalize(
-        #     pytz.utc.localize(datetime.utcnow())
-        # )
-        return datetime.now()
+        return self.tz.normalize(
+            pytz.utc.localize(datetime.utcnow())
+        )

     def is_due(self, last_run_at):
         """Calculate when the next run will take place.

**Comment by AngelLiang** [comment]
感谢反馈。正是这个修改位置。不知有兴趣提交一个PR否？（大佬请喝阔落.jpg）

**Comment by AngelLiang** [comment]
顺便说，在Celery4.3+环境下也有`schedules.crontab()`类似不触发的问题（https://github.com/AngelLiang/celery-sqlalchemy-scheduler/issues/1#issuecomment-495889315），所以我这边建议是Celery 4.2.x，不知道你的Celery版本？（可能这就顺便解决了~）

**Comment by xxxss** [comment]
我用的celery是4.3.0

**Comment by xxxss** [comment]
那么改之后我测了4.2.0和4.3.0，都能正常用。

**Comment by AngelLiang** [comment]
非常感谢！经过一番折腾，我已经发布v0.1.2版本。有空可多多交流。

**Comment by grayguest** [comment]
> 我用的celery是4.3.0

你好，我在4.3.0下成功添加crontab任务，但是无法触发crontab，没有interval(timedelta)任务，想请教一下

**Comment by xxxss** [comment]
> > 我用的celery是4.3.0
> 
> 你好，我在4.3.0下成功添加crontab任务，但是无法触发crontab，没有interval(timedelta)任务，想请教一下

celery-sqlalchemy-scheduler的版本？
怎么添加的crontab任务？
提供一下beat的-debug的日志

**Comment by grayguest** [comment]
@xxxss 是我自己理解有误，是没有问题的。
