### ISSUE TITLE
是否可以动态的添加修改定时任务

### ISSUE THREAD

**Issue by keatsyh** [AngelLiang/celery-sqlalchemy-scheduler#20]

**Comment by AngelLiang** [comment]
可以的，你可以参考[示例代码](https://github.com/AngelLiang/celery-sqlalchemy-scheduler/blob/master/examples/base/tasks.py)前面的docstring。通过SQLAlchemy模型或者数据库动态修改添加。

**Comment by AngelLiang** [comment]
quickstart步骤参考[这里](https://github.com/AngelLiang/celery-sqlalchemy-scheduler/issues/15#issuecomment-625624088)。

**Comment by keatsyh** [comment]
不好意思，这么久才给你回复，按照你的提示已经把问题解决了，很感谢，我可以关闭问题了
